# tune.yml

project_name: "deep-stylometry"
experiment_name: "tune-gpt2-256-se-li-gumbel-dist-autoexp"
do_test: false

# --- tuner ---
num_samples: 1
max_concurrent_trials: 1
time_budget_s: 3600
max_failures: 1

# --- datamodule ---
ds_name: "se" # or halvest
batch_size:
  type: choice
  values: [2, 4]
tokenizer_name: "openai-community/gpt2"
max_length: 128
map_batch_size: 100
load_from_cache_file: true
# config_name: null
mlm_collator: false # only if you use an encoder

# --- model ---
optim_name: "adamw"
base_model_name: "openai-community/gpt2"
is_decoder_model: true
lr:
  type: loguniform
  min: 1.0e-6 # 0.000001
  max: 2.0e-4 # 0.001
dropout: 0.1
weight_decay:
  type: loguniform
  min: 1.0e-6 # 0.000001
  max: 0.01
lm_weight: 1.0
contrastive_weight: 1.0
contrastive_temp:
  type: uniform
  min: 0.01
  max: 1.0
# --- late interaction
do_late_interaction: true
initial_gumbel_temp: 1.0 # null
auto_anneal_gumbel: true
# gumbel_linear_delta: 1e-3
min_gumbel_temp:
  type: uniform
  min: 1.0e-6 # 0.000000001
  max: 1.0e-3 # 0.001
do_distance: true
exp_decay: true
# alpha: 0.5
# project_up: true

# --- wandb logger ---
use_wandb: true
log_model: false

# --- trainer ---
device: "gpu"
num_devices: 1
max_epochs: 5
log_every_n_steps: 1
accumulate_grad_batches:
  type: choice
  values: [8, 16, 32]
gradient_clip_val:
  type: uniform
  min: 1.0e-3 # 0.001
  max: 0.2
precision: "32" # 32-true or bf16-mixed

