name: Code Formatting

on:
  push:
    branches:
      - dev

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.dev.txt

      - name: Run Black
        run: black .

      - name: Run isort
        run: isort .

      - name: Run docformatter
        run: docformatter --in-place -r .

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor: apply code formatting with Black, isort, and docformatter"
