name: Run Tests and Cleanup

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Needed for git history operations

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pytest
          pip install -r requirements.txt

      - name: Run tests
        run: pytest tests/

      - name: Remove requirements.dev.txt from main
        if: github.ref == 'refs/heads/main'
        run: |
          if [ -f requirements.dev.txt ]; then
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
            git checkout main
            git rm requirements.dev.txt
            git commit -m "chore: Remove requirements.dev.txt from main branch"
            git push origin main
            echo "Removed requirements.dev.txt"
          else
            echo "requirements.dev.txt not found"
          fi
